// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcogazwlxpgxhxnozvmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhjb2dhendseHBneGh4bm96dm1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NjM1NjMsImV4cCI6MjA2NjMzOTU2M30.vzeac36WottBZLvKaA_iIpF51CukG2C66mSSbyRh4_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);